name = "wsx-landing"
main = "./src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "wsx.sh"
zone_name = "wsx.sh"

[[routes]]
pattern = "www.wsx.sh"
zone_name = "wsx.sh"

[build]
command = "echo 'No build step required'"


